export const DOMAIN_TEMPLATE_CATALOG = {
  'access-control-roles': {
    templateKey: 'security/access-control',
    screenTemplate: 'settings',
    heroEyebrow: 'Seguranca',
    heroTitle: 'Governanca de perfis e permissoes',
    heroDescription: 'Configure quem pode acessar cada parte da operacao com regras claras por funcao.',
    formCardTitle: 'Matriz de acesso',
    formCardDescription: 'Defina o perfil, o escopo e as permissoes associadas a cada funcao operacional.',
    recordsTitle: 'Perfis configurados',
    recordsEmptyState: 'Nenhum perfil configurado ate o momento.',
    highlights: [
      'Permissoes centralizadas por funcao para reduzir ambiguidade operacional.',
      'Escopo de acesso claro para cada papel da operacao.',
      'Base pronta para auditoria, rastreabilidade e evolucao de seguranca.',
    ],
    profileSummaryTitle: 'Governanca minima',
    profileSummaryDescription: 'Cada perfil deve explicitar permissoes, escopo de acesso e responsabilidade operacional.',
  },
  'ticket-notification-preferences': {
    templateKey: 'support/notification-preferences',
    screenTemplate: 'settings',
    heroEyebrow: 'Notificacoes',
    heroTitle: 'Acompanhe o chamado sem depender do portal',
    heroDescription: 'Configure avisos por e-mail para saber quando o chamado receber atualizacoes importantes.',
    formCardTitle: 'Preferencias de notificacao',
    formCardDescription: 'Defina qual e-mail recebe os alertas e se o acompanhamento por atualizacao do chamado permanece ativo.',
    recordsTitle: 'Preferencias ativas',
    recordsEmptyState: 'Nenhuma preferencia de notificacao configurada ate o momento.',
    highlights: [
      'Avisos por e-mail reduzem a necessidade de acessar o sistema a todo momento.',
      'Configuracao simples para manter a equipe comercial atualizada sobre o andamento do chamado.',
      'Base pronta para expandir notificacoes por status, responsavel e eventos do atendimento.',
    ],
    profileSummaryTitle: 'Rotina de acompanhamento',
    profileSummaryDescription: 'As notificacoes precisam manter o colaborador informado quando o chamado for atualizado.',
  },
  'auth-register': {
    templateKey: 'auth/register',
    screenTemplate: 'wizard',
    heroEyebrow: 'Cadastro',
    heroTitle: 'Crie sua conta',
    heroDescription: 'Cadastre seu acesso com e-mail e senha para comecar a usar a plataforma.',
    formCardTitle: 'Dados de acesso',
    formCardDescription: 'Preencha as credenciais minimas para liberar seu primeiro acesso.',
    recordsTitle: 'Cadastros recentes',
    recordsEmptyState: 'Nenhum cadastro processado ate o momento.',
    highlights: [
      'Validacao imediata de e-mail antes da persistencia.',
      'Senha forte exigida para concluir o cadastro.',
      'Protecao contra e-mails duplicados no fluxo incremental.',
    ],
    profileSummaryTitle: 'Checklist de cadastro',
    profileSummaryDescription: 'O fluxo precisa validar e-mail, senha e evitar duplicidade antes da criacao da conta.',
  },
  'auth-login': {
    templateKey: 'auth/login',
    screenTemplate: 'settings',
    heroEyebrow: 'Autenticacao',
    heroTitle: 'Entre na plataforma',
    heroDescription: 'Use suas credenciais para acessar cursos, progresso e recursos da sua conta.',
    formCardTitle: 'Acesso',
    formCardDescription: 'Informe o e-mail cadastrado e a senha para autenticar a sessao.',
    recordsTitle: 'Sessoes recentes',
    recordsEmptyState: 'Nenhuma sessao registrada ate o momento.',
    highlights: [
      'Validacao de credenciais antes de iniciar a sessao.',
      'Mensagens claras para e-mail ou senha invalidos.',
      'Fluxo pensado para acoplar autenticacao real depois.',
    ],
    profileSummaryTitle: 'Checklist de login',
    profileSummaryDescription: 'A entrada deve validar credenciais e retornar feedback imediato em caso de falha.',
  },
  'profile-settings': {
    templateKey: 'profile/update',
    screenTemplate: 'settings',
    heroEyebrow: 'Perfil',
    heroTitle: 'Atualize seu perfil',
    heroDescription: 'Mantenha nome, foto e dados principais da conta sempre consistentes.',
    formCardTitle: 'Dados do perfil',
    formCardDescription: 'Edite as informacoes visiveis na conta e salve as alteracoes.',
    recordsTitle: 'Historico de alteracoes',
    recordsEmptyState: 'Nenhuma alteracao realizada ate o momento.',
    highlights: [
      'Nome obrigatorio para exibicao correta do perfil.',
      'Foto de perfil com validacao de formato e limite de tamanho.',
      'Historico preparado para auditoria de atualizacoes.',
    ],
    profileSummaryTitle: 'Boas praticas do perfil',
    profileSummaryDescription: 'O aluno precisa manter dados atualizados, com nome obrigatorio e foto valida.',
  },
  'course-catalog': {
    templateKey: 'education/course-catalog',
    screenTemplate: 'crud',
    heroEyebrow: 'Cursos',
    heroTitle: 'Lance um curso com posicionamento forte',
    heroDescription: 'Defina nome, descricao, categoria e preco para abrir uma oferta clara e pronta para vender.',
    formCardTitle: 'Dados do curso',
    formCardDescription: 'Preencha os dados principais da oferta e prepare o curso para publicacao.',
    recordsTitle: 'Meus cursos',
    recordsEmptyState: 'Nenhum curso cadastrado ainda.',
    highlights: [
      'Nome forte e proposta clara elevam a percepcao de valor.',
      'Descricao objetiva ajuda a converter sem gerar duvidas.',
      'Categoria e preco deixam a oferta pronta para vitrine e campanha.',
    ],
    profileSummaryTitle: 'Resumo do curso',
    profileSummaryDescription: 'O curso precisa ter identidade clara, categoria definida e preco pronto para venda.',
  },
  'course-modules': {
    templateKey: 'education/course-modules',
    screenTemplate: 'wizard',
    heroEyebrow: 'Modulos',
    heroTitle: 'Estruture o curso com ritmo e clareza',
    heroDescription: 'Organize o conteudo em modulos bem definidos para tornar a jornada mais intuitiva.',
    formCardTitle: 'Dados do modulo',
    formCardDescription: 'Defina nome, descricao e ordem para cada etapa principal do curso.',
    recordsTitle: 'Modulos existentes',
    recordsEmptyState: 'Nenhum modulo criado ainda.',
    highlights: [
      'Modulos claros ajudam o aluno a entender a progressao do aprendizado.',
      'Descricoes curtas orientam sem poluir a navegacao.',
      'Uma ordem bem definida melhora retencao e conclusao.',
    ],
    profileSummaryTitle: 'Resumo da estrutura',
    profileSummaryDescription: 'Os modulos devem organizar o curso em etapas claras e bem sequenciadas.',
  },
  'course-lessons': {
    templateKey: 'education/course-lessons',
    screenTemplate: 'wizard',
    heroEyebrow: 'Aulas',
    heroTitle: 'Crie aulas mais faceis de consumir',
    heroDescription: 'Associe cada aula ao modulo certo e escolha o formato ideal para o conteudo.',
    formCardTitle: 'Dados da aula',
    formCardDescription: 'Cadastre titulo, formato e modulo de referencia da aula.',
    recordsTitle: 'Aulas cadastradas',
    recordsEmptyState: 'Nenhuma aula adicionada ainda.',
    highlights: [
      'Uma boa organizacao de aulas deixa a trilha mais fluida.',
      'O tipo de midia deve acompanhar a melhor experiencia de aprendizagem.',
      'Titulos claros facilitam busca, navegacao e revisao posterior.',
    ],
    profileSummaryTitle: 'Resumo das aulas',
    profileSummaryDescription: 'As aulas precisam estar vinculadas ao modulo certo e ao formato de midia adequado.',
  },
  'lesson-materials': {
    templateKey: 'education/lesson-materials',
    screenTemplate: 'crud',
    heroEyebrow: 'Materiais',
    heroTitle: 'Entregue materiais que ampliam o valor da aula',
    heroDescription: 'Anexe arquivos, links e recursos de apoio para enriquecer a experiencia do aluno.',
    formCardTitle: 'Dados do material',
    formCardDescription: 'Informe titulo, formato e local de acesso do material complementar.',
    recordsTitle: 'Biblioteca de apoio',
    recordsEmptyState: 'Nenhum material complementar cadastrado ainda.',
    highlights: [
      'Materiais bem curados deixam a aula mais util e memoravel.',
      'Formatos claros ajudam o aluno a saber o que esperar antes do download.',
      'Uma biblioteca organizada reduz friccao e melhora reaproveitamento.',
    ],
    profileSummaryTitle: 'Resumo dos materiais',
    profileSummaryDescription: 'Os materiais complementares devem apoiar a aula com arquivos claros e acessiveis.',
  },
  'course-pricing': {
    templateKey: 'education/course-pricing',
    screenTemplate: 'settings',
    heroEyebrow: 'Precificacao',
    heroTitle: 'Ajuste o valor percebido do curso',
    heroDescription: 'Defina preco, condicoes comerciais e posicionamento para vender com mais clareza.',
    formCardTitle: 'Configuracao comercial',
    formCardDescription: 'Revise o valor e os sinais comerciais que influenciam a conversao da oferta.',
    recordsTitle: 'Historico de precos',
    recordsEmptyState: 'Nenhuma configuracao comercial registrada ainda.',
    highlights: [
      'Preco claro reduz friccao no momento da decisao.',
      'A estrategia comercial precisa reforcar valor, nao so desconto.',
      'Mudancas de preco devem ficar visiveis para acompanhamento futuro.',
    ],
    profileSummaryTitle: 'Resumo comercial',
    profileSummaryDescription: 'A precificacao deve equilibrar valor percebido, conversao e consistencia da oferta.',
  },
  'course-search': {
    templateKey: 'education/course-search',
    screenTemplate: 'dashboard',
    heroEyebrow: 'Busca',
    heroTitle: 'Ajude o aluno a encontrar o curso certo',
    heroDescription: 'Organize filtros e busca por palavra-chave para acelerar descoberta e conversao.',
    formCardTitle: 'Filtros de busca',
    formCardDescription: 'Configure a experiencia de descoberta por nome, categoria e palavras-chave.',
    recordsTitle: 'Resultados encontrados',
    recordsEmptyState: 'Nenhum curso encontrado ainda para os filtros atuais.',
    highlights: [
      'Filtros simples reduzem abandono na descoberta.',
      'Busca por palavra-chave precisa responder com rapidez e clareza.',
      'Categorias bem organizadas melhoram a navegacao do catalogo.',
    ],
    profileSummaryTitle: 'Resumo da descoberta',
    profileSummaryDescription: 'A busca deve facilitar encontrar cursos relevantes com o minimo de friccao.',
  },
  'course-enrollment': {
    templateKey: 'education/course-enrollment',
    screenTemplate: 'wizard',
    heroEyebrow: 'Matriculas',
    heroTitle: 'Libere o acesso certo para cada aluno',
    heroDescription: 'Associe alunos aos cursos corretos e acompanhe o estado das matriculas com controle.',
    formCardTitle: 'Nova matricula',
    formCardDescription: 'Escolha aluno, curso e contexto de liberacao para ativar o acesso com seguranca.',
    recordsTitle: 'Matriculas recentes',
    recordsEmptyState: 'Nenhuma matricula criada ainda.',
    highlights: [
      'Acesso correto evita suporte desnecessario e retrabalho.',
      'Matriculas precisam deixar claro quem entrou em qual curso.',
      'Uma trilha de controle melhora auditoria e suporte operacional.',
    ],
    profileSummaryTitle: 'Resumo de acesso',
    profileSummaryDescription: 'As matriculas devem garantir liberacao correta e rastreavel por aluno e curso.',
  },
  'course-player': {
    templateKey: 'education/course-player',
    screenTemplate: 'dashboard',
    heroEyebrow: 'Consumo',
    heroTitle: 'Entregue uma experiencia fluida de aprendizado',
    heroDescription: 'Reuna midia, progresso e continuidade para o aluno consumir o curso sem friccao.',
    formCardTitle: 'Preferencias do player',
    formCardDescription: 'Acompanhe progresso, formato de consumo e sinais de continuidade da experiencia.',
    recordsTitle: 'Aulas em andamento',
    recordsEmptyState: 'Nenhuma aula em reproducao neste momento.',
    highlights: [
      'O player precisa manter contexto e progresso entre sessoes.',
      'Video, audio e continuidade devem parecer uma experiencia unica.',
      'Consumo fluido aumenta retencao e conclusao das aulas.',
    ],
    profileSummaryTitle: 'Resumo do consumo',
    profileSummaryDescription: 'O aluno precisa consumir aulas e manter progresso com uma experiencia consistente.',
  },
};
