export const DOMAIN_TEMPLATE_CATALOG = {
  'event-schedules': {
    templateKey: 'events/schedules',
    screenTemplate: 'workspace',
    productMode: 'timeline-planner',
    heroEyebrow: 'Planejamento',
    heroTitle: 'Estruture o cronograma do evento',
    heroDescription: 'Monte etapas, prazos e notas operacionais para organizar a execucao do evento com previsibilidade.',
    formCardTitle: 'Nova etapa',
    formCardDescription: 'Registre a etapa com prazo e contexto minimo para orientar a operacao.',
    recordsTitle: 'Etapas do cronograma',
    recordsEmptyState: 'Nenhuma etapa registrada ainda para este evento.',
    highlights: [
      'Etapas claras deixam o handoff entre times mais previsivel.',
      'Prazos visiveis ajudam a antecipar gargalos antes da execucao.',
      'Notas operacionais reduzem ruído na transicao do planejamento para a entrega.',
    ],
    profileSummaryTitle: 'Leitura do planejamento',
    profileSummaryDescription: 'Veja rapidamente quais etapas ja estao planejadas e onde ainda falta contexto operacional.',
  },
  'event-suppliers': {
    templateKey: 'events/suppliers',
    screenTemplate: 'workspace',
    productMode: 'vendor-registry',
    heroEyebrow: 'Operacao',
    heroTitle: 'Centralize fornecedores do evento',
    heroDescription: 'Cadastre parceiros com categoria de servico e contatos principais para acionar a operacao com mais rapidez.',
    formCardTitle: 'Novo fornecedor',
    formCardDescription: 'Registre o parceiro com o minimo de contexto necessario para reutilizacao futura.',
    recordsTitle: 'Fornecedores cadastrados',
    recordsEmptyState: 'Nenhum fornecedor registrado ainda para esta operacao.',
    highlights: [
      'Categorias claras ajudam a localizar o parceiro certo sem retrabalho.',
      'Contatos principais deixam o acionamento operacional mais rapido.',
      'Base centralizada para reaproveitar fornecedores entre eventos.',
    ],
    profileSummaryTitle: 'Resumo operacional',
    profileSummaryDescription: 'Veja rapidamente quais categorias ja estao cobertas e quais parceiros estao prontos para acionamento.',
  },
  'visit-operational-responsibles': {
    templateKey: 'visits/operational-responsibles',
    screenTemplate: 'workspace',
    productMode: 'operations-registry',
    heroEyebrow: 'Recepcao',
    heroTitle: 'Cadastre responsaveis operacionais da visita',
    heroDescription: 'Mantenha nome, contato e tipo de suporte de quem apoia a operacao para agir rapido quando a visita acontecer.',
    formCardTitle: 'Novo responsavel operacional',
    formCardDescription: 'Registre apenas o essencial para que a recepcao e a seguranca saibam quem acionar.',
    recordsTitle: 'Responsaveis operacionais',
    recordsEmptyState: 'Nenhum responsavel operacional cadastrado ainda para esta operacao.',
    highlights: [
      'Nome e contato certos reduzem retrabalho quando a visita exige apoio imediato.',
      'Tipo de suporte padronizado ajuda a recepcao a encontrar a pessoa certa mais rapido.',
      'Rede de apoio pronta para reutilizacao entre visitas e turnos.',
    ],
    profileSummaryTitle: 'Leitura da operacao',
    profileSummaryDescription: 'Veja rapidamente quem apoia a visita, como acionar e qual papel cada responsavel desempenha.',
  },
  'visit-intake': {
    templateKey: 'visits/intake',
    screenTemplate: 'crud',
    productMode: 'operations-workspace',
    heroEyebrow: 'Visitas',
    heroTitle: 'Crie uma nova visita',
    heroDescription: 'Registre nome, objetivo, data prevista e contexto inicial para abrir a visita com clareza operacional.',
    formCardTitle: 'Dados da visita',
    formCardDescription: 'Informe os dados essenciais para que a recepcao inicie a triagem sem retrabalho.',
    recordsTitle: 'Visitas em andamento',
    recordsEmptyState: 'Nenhuma visita iniciada ainda. Assim que a primeira entrar, ela aparecera aqui com contexto e proximo passo.',
    highlights: [
      'Nome, objetivo e data precisam aparecer juntos para a recepcao entender a demanda.',
      'O contexto inicial deve orientar a triagem sem depender de alinhamento adicional imediato.',
      'A tela deve parecer o inicio de uma visita real, nao um cadastro generico.',
    ],
    profileSummaryTitle: 'Leitura da visita',
    profileSummaryDescription: 'Veja rapidamente o status, o objetivo e o contexto inicial de cada visita aberta.',
  },
  'visit-recurring-history': {
    templateKey: 'visits/recurring-history',
    screenTemplate: 'workspace',
    productMode: 'evidence-workbench',
    heroEyebrow: 'Historico',
    heroTitle: 'Consulte visitas recorrentes',
    heroDescription: 'Visualize o historico recente do cliente para reaproveitar contexto e agilizar um novo agendamento.',
    formCardTitle: 'Buscar historico',
    formCardDescription: 'Informe o cliente e ajuste o recorte operacional para localizar visitas anteriores com rapidez.',
    recordsTitle: 'Visitas encontradas',
    recordsEmptyState: 'Nenhum historico localizado ainda para o cliente informado.',
    highlights: [
      'A busca deve mostrar visitas recentes com contexto suficiente para novo agendamento.',
      'O historico precisa privilegiar leitura rapida de datas, visitante principal e tipo de visita.',
      'A tela deve ajudar a reaproveitar dados sem parecer um cadastro generico.',
    ],
    profileSummaryTitle: 'Consulta operacional',
    profileSummaryDescription: 'Veja rapidamente quais visitas podem servir de base para um novo agendamento do cliente recorrente.',
  },
  'visit-extra-companions': {
    templateKey: 'visits/extra-companions',
    screenTemplate: 'workspace',
    productMode: 'approval-flow',
    heroEyebrow: 'Visitas',
    heroTitle: 'Inclua acompanhantes extras na visita',
    heroDescription: 'Adicione consultores e acompanhantes em visitas ja aprovadas sem reiniciar todo o fluxo de liberacao.',
    formCardTitle: 'Novo acompanhante extra',
    formCardDescription: 'Vincule o acompanhante a uma visita aprovada e registre a decisao rapida da seguranca.',
    recordsTitle: 'Acompanhantes vinculados',
    recordsEmptyState: 'Nenhum acompanhante extra registrado ainda para visitas aprovadas.',
    highlights: [
      'A inclusao precisa apontar para uma visita ja aprovada, sem reabrir o processo inteiro.',
      'A decisao rapida da seguranca deve ficar visivel para evitar duvida operacional na recepcao.',
      'A lista deve parecer extensao da visita, nao um cadastro isolado sem contexto.',
    ],
    profileSummaryTitle: 'Inclusoes recentes',
    profileSummaryDescription: 'Veja rapidamente quais acompanhantes extras ja foram vinculados e como a seguranca decidiu cada caso.',
  },
  'visit-approval-cutoff-settings': {
    templateKey: 'visits/approval-cutoff-settings',
    screenTemplate: 'settings',
    productMode: 'governance-console',
    heroEyebrow: 'Aprovacao',
    heroTitle: 'Configure o horario limite de aprovacao',
    heroDescription: 'Defina o horario diario usado para bloquear visitas de ultima hora sem tempo de analise operacional.',
    formCardTitle: 'Horario limite',
    formCardDescription: 'Ajuste o horario principal aplicado ao recebimento de solicitacoes de visita.',
    recordsTitle: 'Configuracao vigente',
    recordsEmptyState: 'Nenhum horario limite configurado ainda.',
    highlights: [
      'A regra precisa ser simples, visivel e facil de revisar pelo gestor administrativo.',
      'A configuracao vigente deve deixar claro qual horario esta valendo no sistema.',
      'A tela deve parecer configuracao operacional, nao cadastro generico.',
    ],
    profileSummaryTitle: 'Politica atual',
    profileSummaryDescription: 'Veja rapidamente qual horario esta em vigor e quando a regra foi atualizada por ultimo.',
  },
  'access-control-roles': {
    templateKey: 'security/access-control',
    screenTemplate: 'settings',
    productMode: 'governance-console',
    heroEyebrow: 'Seguran?a',
    heroTitle: 'Perfis de acesso por funcao',
    heroDescription: 'Organize quem pode atender, reclassificar, acompanhar indicadores e administrar a operacao.',
    formCardTitle: 'Novo perfil',
    formCardDescription: 'Defina a funcao, o alcance do acesso e as permissoes principais deste perfil.',
    recordsTitle: 'Perfis configurados',
    recordsEmptyState: 'Nenhum perfil configurado at? o momento.',
    highlights: [
      'Perfis com escopo claro para cada papel da operacao.',
      'Escopo de acesso claro para cada papel da operacao.',
      'Governanca visivel para facilitar revisao futura.',
    ],
    profileSummaryTitle: 'Resumo dos acessos',
    profileSummaryDescription: 'Veja rapidamente quais perfis estao ativos e como o acesso esta distribuido.',
  },
  'ticket-notification-preferences': {
    templateKey: 'support/notification-preferences',
    screenTemplate: 'settings',
    productMode: 'self-service-settings',
    heroEyebrow: 'Notificacoes',
    heroTitle: 'Acompanhe o chamado sem depender do portal',
    heroDescription: 'Ajuste o e-mail principal e o recebimento de alertas para acompanhar seus chamados sem depender do portal o tempo todo.',
    formCardTitle: 'Preferencias de notificacao',
    formCardDescription: 'Defina qual e-mail recebe os avisos e se os alertas de atualizacao permanecem ativos.',
    recordsTitle: 'Preferencias ativas',
    recordsEmptyState: 'Nenhuma preferencia de notificacao configurada at? o momento.',
    highlights: [
      'O colaborador entende rapidamente se esta sendo avisado ou nao.',
      'A configuracao destaca o e-mail principal e o estado dos alertas.',
      'A tela explica o beneficio do ajuste sem soar tecnica.',
    ],
    profileSummaryTitle: 'Resumo atual',
    profileSummaryDescription: 'Entenda rapidamente se os alertas estao ativos e para qual e-mail eles serao enviados.',
  },
  'support-ticket-attachments': {
    templateKey: 'support/ticket-attachments',
    screenTemplate: 'workspace',
    productMode: 'evidence-workbench',
    heroEyebrow: 'Anexos',
    heroTitle: 'Adicione comprovantes ao chamado sem perder contexto',
    heroDescription: 'Envie documentos fiscais e arquivos de apoio para acelerar a triagem e reduzir retrabalho no atendimento.',
    formCardTitle: 'Novo anexo',
    formCardDescription: 'Preencha os dados do documento para registrar o contexto do caso de forma clara.',
    recordsTitle: 'Anexos do chamado',
    recordsEmptyState: 'Nenhum documento vinculado a este chamado at? o momento.',
    highlights: [
      'Comprovantes fiscais deixam a triagem mais rapida e objetiva.',
      'O anexo certo reduz trocas de e-mail e retrabalho entre solicitante e atendimento.',
      'Acervo organizado para facilitar a analise do caso.',
    ],
    profileSummaryTitle: 'Contexto do envio',
    profileSummaryDescription: 'Confirme se o documento certo esta sendo enviado com contexto suficiente para agilizar a analise.',
  },
  'support-performance-dashboard': {
    templateKey: 'support/performance-dashboard',
    screenTemplate: 'dashboard',
    productMode: 'manager-cockpit',
    heroEyebrow: 'Operacoes',
    heroTitle: 'Painel de desempenho do atendimento',
    heroDescription: 'Acompanhe volume de chamados, categorias mais demandadas e status para decidir onde agir primeiro.',
    formCardTitle: 'Filtros da leitura',
    formCardDescription: 'Refine o recorte do painel para comparar categorias, status e periodo com mais clareza.',
    recordsTitle: 'Recortes principais',
    recordsEmptyState: 'Nenhum indicador consolidado ainda para os filtros atuais.',
    highlights: [
      'Volume por categoria e status com leitura executiva imediata.',
      'Recortes prontos para identificar gargalos e desvios do atendimento.',
      'Painel pensado para decisao gerencial, nao para operacao de cadastro.',
    ],
    profileSummaryTitle: 'Leitura principal',
    profileSummaryDescription: 'Os indicadores devem mostrar rapidamente onde a operacao exige mais atencao.',
  },
  'auth-register': {
    templateKey: 'auth/register',
    screenTemplate: 'wizard',
    productMode: 'onboarding-flow',
    heroEyebrow: 'Cadastro',
    heroTitle: 'Crie sua conta',
    heroDescription: 'Cadastre seu acesso com e-mail e senha para comecar a usar a plataforma.',
    formCardTitle: 'Dados de acesso',
    formCardDescription: 'Preencha as credenciais minimas para liberar seu primeiro acesso.',
    recordsTitle: 'Cadastros recentes',
    recordsEmptyState: 'Nenhum cadastro processado at? o momento.',
    highlights: [
      'Valida??o imediata de e-mail antes da persist?ncia.',
      'Senha forte exigida para concluir o cadastro.',
      'Protecao contra e-mails duplicados no fluxo incremental.',
    ],
    profileSummaryTitle: 'Checklist de cadastro',
    profileSummaryDescription: 'O fluxo precisa validar e-mail, senha e evitar duplicidade antes da criacao da conta.',
  },
  'auth-login': {
    templateKey: 'auth/login',
    screenTemplate: 'settings',
    productMode: 'access-gateway',
    heroEyebrow: 'Autentica??o',
    heroTitle: 'Entre na plataforma',
    heroDescription: 'Use suas credenciais para acessar cursos, progresso e recursos da sua conta.',
    formCardTitle: 'Acesso',
    formCardDescription: 'Informe o e-mail cadastrado e a senha para autenticar a sess?o.',
    recordsTitle: 'Sessoes recentes',
    recordsEmptyState: 'Nenhuma sess?o registrada at? o momento.',
    highlights: [
      'Valida??o de credenciais antes de iniciar a sess?o.',
      'Mensagens claras para e-mail ou senha invalidos.',
      'Fluxo pensado para acoplar autentica?o real depois.',
    ],
    profileSummaryTitle: 'Checklist de login',
    profileSummaryDescription: 'A entrada deve validar credenciais e retornar feedback imediato em caso de falha.',
  },
  'profile-settings': {
    templateKey: 'profile/update',
    screenTemplate: 'settings',
    productMode: 'self-service-settings',
    heroEyebrow: 'Perfil',
    heroTitle: 'Atualize seu perfil',
    heroDescription: 'Mantenha nome, foto e dados principais da conta sempre consistentes.',
    formCardTitle: 'Dados do perfil',
    formCardDescription: 'Edite as informacoes visiveis na conta e salve as altera??es.',
    recordsTitle: 'Hist?rico de altera??es',
    recordsEmptyState: 'Nenhuma alteracao realizada at? o momento.',
    highlights: [
      'Nome obrigatorio para exibicao correta do perfil.',
      'Foto de perfil com valida?o de formato e limite de tamanho.',
      'Hist?rico preparado para auditoria de atualizacoes.',
    ],
    profileSummaryTitle: 'Boas praticas do perfil',
    profileSummaryDescription: 'O aluno precisa manter dados atualizados, com nome obrigatorio e foto valida.',
  },
  'course-catalog': {
    templateKey: 'education/course-catalog',
    screenTemplate: 'crud',
    productMode: 'catalog-builder',
    heroEyebrow: 'Cursos',
    heroTitle: 'Lance um curso com posicionamento forte',
    heroDescription: 'Defina nome, descricao, categoria e preco para abrir uma oferta clara e pronta para vender.',
    formCardTitle: 'Dados do curso',
    formCardDescription: 'Preencha os dados principais da oferta e prepare o curso para publica??o.',
    recordsTitle: 'Meus cursos',
    recordsEmptyState: 'Nenhum curso cadastrado ainda.',
    highlights: [
      'Nome forte e proposta clara elevam a percepcao de valor.',
      'Descricao objetiva ajuda a converter sem gerar duvidas.',
      'Categoria e preco deixam a oferta pronta para vitrine e campanha.',
    ],
    profileSummaryTitle: 'Resumo do curso',
    profileSummaryDescription: 'O curso precisa ter identidade clara, categoria definida e preco pronto para venda.',
  },
  'course-modules': {
    templateKey: 'education/course-modules',
    screenTemplate: 'wizard',
    productMode: 'curriculum-designer',
    heroEyebrow: 'M?dulos',
    heroTitle: 'Estruture o curso com ritmo e clareza',
    heroDescription: 'Organize o conte?do em m?dulos bem definidos para tornar a jornada mais intuitiva.',
    formCardTitle: 'Dados do m?dulo',
    formCardDescription: 'Defina nome, descricao e ordem para cada etapa principal do curso.',
    recordsTitle: 'M?dulos existentes',
    recordsEmptyState: 'Nenhum m?dulo criado ainda.',
    highlights: [
      'M?dulos claros ajudam o aluno a entender a progress?o do aprendizado.',
      'Descri??es curtas orientam sem poluir a navega??o.',
      'Uma ordem bem definida melhora retencao e conclusao.',
    ],
    profileSummaryTitle: 'Resumo da estrutura',
    profileSummaryDescription: 'Os m?dulos devem organizar o curso em etapas claras e bem sequenciadas.',
  },
  'course-lessons': {
    templateKey: 'education/course-lessons',
    screenTemplate: 'wizard',
    productMode: 'curriculum-designer',
    heroEyebrow: 'Aulas',
    heroTitle: 'Crie aulas mais faceis de consumir',
    heroDescription: 'Associe cada aula ao m?dulo certo e escolha o formato ideal para o conte?do.',
    formCardTitle: 'Dados da aula',
    formCardDescription: 'Cadastre t?tulo, formato e m?dulo de refer?ncia da aula.',
    recordsTitle: 'Aulas cadastradas',
    recordsEmptyState: 'Nenhuma aula adicionada ainda.',
    highlights: [
      'Uma boa organizacao de aulas deixa a trilha mais fluida.',
      'O tipo de m?dia deve acompanhar a melhor experi?ncia de aprendizagem.',
      'Titulos claros facilitam busca, navega??o e revis?o posterior.',
    ],
    profileSummaryTitle: 'Resumo das aulas',
    profileSummaryDescription: 'As aulas precisam estar vinculadas ao m?dulo certo e ao formato de m?dia adequado.',
  },
  'lesson-materials': {
    templateKey: 'education/lesson-materials',
    screenTemplate: 'crud',
    productMode: 'asset-library',
    heroEyebrow: 'Materiais',
    heroTitle: 'Entregue materiais que ampliam o valor da aula',
    heroDescription: 'Anexe arquivos, links e recursos de apoio para enriquecer a experi?ncia do aluno.',
    formCardTitle: 'Dados do material',
    formCardDescription: 'Informe titulo, formato e local de acesso do material complementar.',
    recordsTitle: 'Biblioteca de apoio',
    recordsEmptyState: 'Nenhum material complementar cadastrado ainda.',
    highlights: [
      'Materiais bem curados deixam a aula mais util e memoravel.',
      'Formatos claros ajudam o aluno a saber o que esperar antes do download.',
      'Uma biblioteca organizada reduz fric??o e melhora reaproveitamento.',
    ],
    profileSummaryTitle: 'Resumo dos materiais',
    profileSummaryDescription: 'Os materiais complementares devem apoiar a aula com arquivos claros e acessiveis.',
  },
  'course-pricing': {
    templateKey: 'education/course-pricing',
    screenTemplate: 'settings',
    productMode: 'commercial-settings',
    heroEyebrow: 'Precificacao',
    heroTitle: 'Ajuste o valor percebido do curso',
    heroDescription: 'Defina preco, condicoes comerciais e posicionamento para vender com mais clareza.',
    formCardTitle: 'Configuracao comercial',
    formCardDescription: 'Revise o valor e os sinais comerciais que influenciam a conversao da oferta.',
    recordsTitle: 'Hist?rico de pre?os',
    recordsEmptyState: 'Nenhuma configuracao comercial registrada ainda.',
    highlights: [
      'Preco claro reduz fric??o no momento da decisao.',
      'A estrat?gia comercial precisa reforcar valor, n?o so desconto.',
      'Mudan?as de preco devem ficar visiveis para acompanhamento futuro.',
    ],
    profileSummaryTitle: 'Resumo comercial',
    profileSummaryDescription: 'A precificacao deve equilibrar valor percebido, conversao e consistencia da oferta.',
  },
  'course-search': {
    templateKey: 'education/course-search',
    screenTemplate: 'dashboard',
    productMode: 'manager-cockpit',
    heroEyebrow: 'Busca',
    heroTitle: 'Ajude o aluno a encontrar o curso certo',
    heroDescription: 'Organize filtros e busca por palavra-chave para acelerar descoberta e conversao.',
    formCardTitle: 'Filtros de busca',
    formCardDescription: 'Configure a experi?ncia de descoberta por nome, categoria e palavras-chave.',
    recordsTitle: 'Resultados encontrados',
    recordsEmptyState: 'Nenhum curso encontrado ainda para os filtros atuais.',
    highlights: [
      'Filtros simples reduzem abandono na descoberta.',
      'Busca por palavra-chave precisa responder com rapidez e clareza.',
      'Categorias bem organizadas melhoram a navega??o do catalogo.',
    ],
    profileSummaryTitle: 'Resumo da descoberta',
    profileSummaryDescription: 'A busca deve facilitar encontrar cursos relevantes com o minimo de fric??o.',
  },
  'course-enrollment': {
    templateKey: 'education/course-enrollment',
    screenTemplate: 'wizard',
    productMode: 'review-workbench',
    heroEyebrow: 'Matriculas',
    heroTitle: 'Libere o acesso certo para cada aluno',
    heroDescription: 'Associe alunos aos cursos corretos e acompanhe o estado das matriculas com controle.',
    formCardTitle: 'Nova matricula',
    formCardDescription: 'Escolha aluno, curso e contexto de liberacao para ativar o acesso com seguran?a.',
    recordsTitle: 'Matriculas recentes',
    recordsEmptyState: 'Nenhuma matricula criada ainda.',
    highlights: [
      'Acesso correto evita suporte desnecessario e retrabalho.',
      'Matriculas precisam deixar claro quem entrou em qual curso.',
      'Uma trilha de controle melhora auditoria e suporte operacional.',
    ],
    profileSummaryTitle: 'Resumo de acesso',
    profileSummaryDescription: 'As matriculas devem garantir liberacao correta e rastreavel por aluno e curso.',
  },
  'course-player': {
    templateKey: 'education/course-player',
    screenTemplate: 'dashboard',
    productMode: 'immersive-workspace',
    heroEyebrow: 'Consumo',
    heroTitle: 'Entregue uma experi?ncia fluida de aprendizado',
    heroDescription: 'Reuna m?dia, progresso e continuidade para o aluno consumir o curso sem fric??o.',
    formCardTitle: 'Preferencias do player',
    formCardDescription: 'Acompanhe progresso, formato de consumo e sinais de continuidade da experi?ncia.',
    recordsTitle: 'Aulas em andamento',
    recordsEmptyState: 'Nenhuma aula em reproducao neste momento.',
    highlights: [
      'O player precisa manter contexto e progresso entre sess?es.',
      'Video, audio e continuidade devem parecer uma experi?ncia ?nica.',
      'Consumo fluido aumenta retencao e conclusao das aulas.',
    ],
    profileSummaryTitle: 'Resumo do consumo',
    profileSummaryDescription: 'O aluno precisa consumir aulas e manter progresso com uma experi?ncia consistente.',
  },
};
