export const DOMAIN_TEMPLATE_CATALOG = {
  'auth-register': {
    templateKey: 'auth/register',
    screenTemplate: 'wizard',
    heroEyebrow: 'Cadastro',
    heroTitle: 'Crie sua conta',
    heroDescription: 'Cadastre seu acesso com e-mail e senha para comecar a usar a plataforma.',
    formCardTitle: 'Dados de acesso',
    formCardDescription: 'Preencha as credenciais minimas para liberar seu primeiro acesso.',
    recordsTitle: 'Cadastros recentes',
    recordsEmptyState: 'Nenhum cadastro processado ate o momento.',
    highlights: [
      'Validacao imediata de e-mail antes da persistencia.',
      'Senha forte exigida para concluir o cadastro.',
      'Protecao contra e-mails duplicados no fluxo incremental.',
    ],
    profileSummaryTitle: 'Checklist de cadastro',
    profileSummaryDescription: 'O fluxo precisa validar e-mail, senha e evitar duplicidade antes da criacao da conta.',
  },
  'auth-login': {
    templateKey: 'auth/login',
    screenTemplate: 'settings',
    heroEyebrow: 'Autenticacao',
    heroTitle: 'Entre na plataforma',
    heroDescription: 'Use suas credenciais para acessar cursos, progresso e recursos da sua conta.',
    formCardTitle: 'Acesso',
    formCardDescription: 'Informe o e-mail cadastrado e a senha para autenticar a sessao.',
    recordsTitle: 'Sessoes recentes',
    recordsEmptyState: 'Nenhuma sessao registrada ate o momento.',
    highlights: [
      'Validacao de credenciais antes de iniciar a sessao.',
      'Mensagens claras para e-mail ou senha invalidos.',
      'Fluxo pensado para acoplar autenticacao real depois.',
    ],
    profileSummaryTitle: 'Checklist de login',
    profileSummaryDescription: 'A entrada deve validar credenciais e retornar feedback imediato em caso de falha.',
  },
  'profile-settings': {
    templateKey: 'profile/update',
    screenTemplate: 'settings',
    heroEyebrow: 'Perfil',
    heroTitle: 'Atualize seu perfil',
    heroDescription: 'Mantenha nome, foto e dados principais da conta sempre consistentes.',
    formCardTitle: 'Dados do perfil',
    formCardDescription: 'Edite as informacoes visiveis na conta e salve as alteracoes.',
    recordsTitle: 'Historico de alteracoes',
    recordsEmptyState: 'Nenhuma alteracao realizada ate o momento.',
    highlights: [
      'Nome obrigatorio para exibicao correta do perfil.',
      'Foto de perfil com validacao de formato e limite de tamanho.',
      'Historico preparado para auditoria de atualizacoes.',
    ],
    profileSummaryTitle: 'Boas praticas do perfil',
    profileSummaryDescription: 'O aluno precisa manter dados atualizados, com nome obrigatorio e foto valida.',
  },
  'course-catalog': {
    templateKey: 'education/course-catalog',
    screenTemplate: 'crud',
    heroEyebrow: 'Cursos',
    heroTitle: 'Lance um curso com posicionamento forte',
    heroDescription: 'Defina nome, descricao, categoria e preco para abrir uma oferta clara e pronta para vender.',
    formCardTitle: 'Dados do curso',
    formCardDescription: 'Preencha os dados principais da oferta e prepare o curso para publicacao.',
    recordsTitle: 'Meus cursos',
    recordsEmptyState: 'Nenhum curso cadastrado ainda.',
    highlights: [
      'Nome forte e proposta clara elevam a percepcao de valor.',
      'Descricao objetiva ajuda a converter sem gerar duvidas.',
      'Categoria e preco deixam a oferta pronta para vitrine e campanha.',
    ],
    profileSummaryTitle: 'Resumo do curso',
    profileSummaryDescription: 'O curso precisa ter identidade clara, categoria definida e preco pronto para venda.',
  },
  'course-modules': {
    templateKey: 'education/course-modules',
    screenTemplate: 'wizard',
    heroEyebrow: 'Modulos',
    heroTitle: 'Estruture o curso com ritmo e clareza',
    heroDescription: 'Organize o conteudo em modulos bem definidos para tornar a jornada mais intuitiva.',
    formCardTitle: 'Dados do modulo',
    formCardDescription: 'Defina nome, descricao e ordem para cada etapa principal do curso.',
    recordsTitle: 'Modulos existentes',
    recordsEmptyState: 'Nenhum modulo criado ainda.',
    highlights: [
      'Modulos claros ajudam o aluno a entender a progressao do aprendizado.',
      'Descricoes curtas orientam sem poluir a navegacao.',
      'Uma ordem bem definida melhora retencao e conclusao.',
    ],
    profileSummaryTitle: 'Resumo da estrutura',
    profileSummaryDescription: 'Os modulos devem organizar o curso em etapas claras e bem sequenciadas.',
  },
  'course-lessons': {
    templateKey: 'education/course-lessons',
    screenTemplate: 'wizard',
    heroEyebrow: 'Aulas',
    heroTitle: 'Crie aulas mais faceis de consumir',
    heroDescription: 'Associe cada aula ao modulo certo e escolha o formato ideal para o conteudo.',
    formCardTitle: 'Dados da aula',
    formCardDescription: 'Cadastre titulo, formato e modulo de referencia da aula.',
    recordsTitle: 'Aulas cadastradas',
    recordsEmptyState: 'Nenhuma aula adicionada ainda.',
    highlights: [
      'Uma boa organizacao de aulas deixa a trilha mais fluida.',
      'O tipo de midia deve acompanhar a melhor experiencia de aprendizagem.',
      'Titulos claros facilitam busca, navegacao e revisao posterior.',
    ],
    profileSummaryTitle: 'Resumo das aulas',
    profileSummaryDescription: 'As aulas precisam estar vinculadas ao modulo certo e ao formato de midia adequado.',
  },
  'lesson-materials': {
    templateKey: 'education/lesson-materials',
    screenTemplate: 'crud',
    heroEyebrow: 'Materiais',
    heroTitle: 'Entregue materiais que ampliam o valor da aula',
    heroDescription: 'Anexe arquivos, links e recursos de apoio para enriquecer a experiencia do aluno.',
    formCardTitle: 'Dados do material',
    formCardDescription: 'Informe titulo, formato e local de acesso do material complementar.',
    recordsTitle: 'Biblioteca de apoio',
    recordsEmptyState: 'Nenhum material complementar cadastrado ainda.',
    highlights: [
      'Materiais bem curados deixam a aula mais util e memoravel.',
      'Formatos claros ajudam o aluno a saber o que esperar antes do download.',
      'Uma biblioteca organizada reduz friccao e melhora reaproveitamento.',
    ],
    profileSummaryTitle: 'Resumo dos materiais',
    profileSummaryDescription: 'Os materiais complementares devem apoiar a aula com arquivos claros e acessiveis.',
  },
};
